version: '3.1'
services:
  stats-server:
    build: ./stats/stats-server
    image: stats-server-dock
    container_name: stats-server
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/explorewithme
      - SPRING_DATASOURCE_USER=root
      - SPRING_DATASOURCE_PASS=root

  stats-db:
    image: postgres:14-alpine
    container_name: stats-db
    ports:
      - "6540:5432"
    environment:
      - POSTGRES_DB=explorewithme
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_HOST=stats-db
      - POSTGRES_PORT=5432

  ewm-service:
    build: ./main-service
    image: ewm-service-dock
    container_name: ewm-service
    ports:
      - "8080:8080"
    depends_on:
      - stats-server
      - ewm-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/explorewithme
      - SPRING_DATASOURCE_USER=root
      - SPRING_DATASOURCE_PASS=root

  ewm-db:
    image: postgres:14-alpine
    container_name: ewm-db
    ports:
      - "6541:5432"
    depends_on:
      - stats-db
    environment:
      - POSTGRES_DB=explorewithme
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_HOST=ewm-db
      - POSTGRES_PORT=5432
